/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kxbjava;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime; 
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author User
 */
public class APUManageCustomer extends javax.swing.JFrame {
    
    private final String CustPrefix = "CUST";
    private String FileDir, CustID, uID, uUsername;
    private int newCustID;
    private DefaultComboBoxModel CustList;
    private final Color ogtxt = new Color(237,237,237);
            
    
    /**
     * Creates new form APUManageUserProfile
     */
    public APUManageCustomer() {
        initComponents();
        loadUserProfile();
        initForm();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        txtDOB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaHomeAddress = new javax.swing.JTextArea();
        txtManagerID = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cmbCustID = new javax.swing.JComboBox<>();
        txtFullName = new javax.swing.JTextField();
        lblCustomerID = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblManagerID = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(68, 68, 68));

        lblTitle.setBackground(new java.awt.Color(68, 68, 68));
        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(218, 0, 55));
        lblTitle.setText("Customer Management");

        cmbGender.setBackground(new java.awt.Color(8, 217, 214));
        cmbGender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbGender.setForeground(new java.awt.Color(68, 68, 68));
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        cmbGender.setToolTipText("Customer Gender");
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });

        txtDOB.setBackground(new java.awt.Color(68, 68, 68));
        txtDOB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDOB.setToolTipText("Customer Email");
        txtDOB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(237, 237, 237)));
        txtDOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDOBFocusLost(evt);
            }
        });

        txaHomeAddress.setBackground(new java.awt.Color(68, 68, 68));
        txaHomeAddress.setColumns(20);
        txaHomeAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txaHomeAddress.setForeground(new java.awt.Color(237, 237, 237));
        txaHomeAddress.setRows(5);
        txaHomeAddress.setToolTipText("Customer Home Address");
        txaHomeAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(237, 237, 237)));
        jScrollPane1.setViewportView(txaHomeAddress);

        txtManagerID.setEditable(false);
        txtManagerID.setBackground(new java.awt.Color(68, 68, 68));
        txtManagerID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtManagerID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(237, 237, 237)));

        btnRegister.setBackground(new java.awt.Color(23, 23, 23));
        btnRegister.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(237, 237, 237));
        btnRegister.setText("Register");
        btnRegister.setBorder(null);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(23, 23, 23));
        btnUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(237, 237, 237));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(23, 23, 23));
        btnDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(237, 237, 237));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cmbCustID.setBackground(new java.awt.Color(8, 217, 214));
        cmbCustID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbCustID.setForeground(new java.awt.Color(68, 68, 68));
        cmbCustID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Existing Customer" }));
        cmbCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustIDActionPerformed(evt);
            }
        });

        txtFullName.setBackground(new java.awt.Color(68, 68, 68));
        txtFullName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtFullName.setToolTipText("Customer Full Name");
        txtFullName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(237, 237, 237)));

        lblCustomerID.setBackground(new java.awt.Color(68, 68, 68));
        lblCustomerID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCustomerID.setForeground(new java.awt.Color(237, 237, 237));
        lblCustomerID.setText("Customer ID:");

        lblHomeAddress.setBackground(new java.awt.Color(68, 68, 68));
        lblHomeAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHomeAddress.setForeground(new java.awt.Color(237, 237, 237));
        lblHomeAddress.setText("Home Address:");

        lblFullName.setBackground(new java.awt.Color(68, 68, 68));
        lblFullName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(237, 237, 237));
        lblFullName.setText("Full Name:");

        lblGender.setBackground(new java.awt.Color(68, 68, 68));
        lblGender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(237, 237, 237));
        lblGender.setText("Gender:");

        lblManagerID.setBackground(new java.awt.Color(68, 68, 68));
        lblManagerID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblManagerID.setForeground(new java.awt.Color(237, 237, 237));
        lblManagerID.setText("Manager ID:");

        lblPhoneNumber.setBackground(new java.awt.Color(68, 68, 68));
        lblPhoneNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(237, 237, 237));
        lblPhoneNumber.setText("Phone Number:");

        lblDOB.setBackground(new java.awt.Color(68, 68, 68));
        lblDOB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(237, 237, 237));
        lblDOB.setText("Date of Birth:");

        lblEmail.setBackground(new java.awt.Color(68, 68, 68));
        lblEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(237, 237, 237));
        lblEmail.setText("Email:");

        txtPhoneNumber.setBackground(new java.awt.Color(68, 68, 68));
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(222, 222, 222)));
        try {
            txtPhoneNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPhoneNumber.setText("");
        txtPhoneNumber.setToolTipText("Customer Phone Number");
        txtPhoneNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtEmail.setBackground(new java.awt.Color(68, 68, 68));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEmail.setToolTipText("Customer Email");
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(237, 237, 237)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblCustomerID)
                        .addGap(296, 296, 296)
                        .addComponent(lblFullName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhoneNumber)
                                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender)
                                    .addComponent(txtManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblManagerID)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(136, 136, 136)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHomeAddress)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141)
                                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblEmail)
                        .addGap(342, 342, 342)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOB))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblTitle)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomerID)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblFullName)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblHomeAddress)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumber)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lblGender)
                        .addGap(18, 18, 18)
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDOB))
                    .addComponent(lblEmail))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(lblManagerID)
                .addGap(40, 40, 40)
                .addComponent(txtManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //<editor-fold defaultstate="collapsed" desc="Methods">
    
    private void loadUserProfile(){
        String[] matchedID = null;
        FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
        File usertext = new File(FileDir + "UserCache.txt");
        Scanner intUser;
        try {
            intUser = new Scanner(usertext);
            while (intUser.hasNext())
            {
             String bEntry = intUser.nextLine();
             matchedID = bEntry.split(":");
             uID = matchedID[0];
             uUsername = matchedID[3];
                }
            intUser.close();
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setCustomerID(){
        // This is to ensure the entire method have access to borrow matchedID array
        String[] matchedID = null;
        CustList = new DefaultComboBoxModel();
//        String cLabel; // Declared to store title of the selected client type
//        switch (cspecies) {
//            case "STA":
//                cLabel = "Staff";
//                break;
//            case "STU":
//                cLabel = "Student";
//                break;
//            default:
//                cLabel = "Existing";
//        }
        // Adding default text
        CustList.addElement("Select Customer ID");
        cmbCustID.setModel(CustList);
        FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
        // For debugging purpose only
        // JOptionPane.showMessageDialog(null, bID);
        File customertxt = new File(FileDir + "Customer.txt");
        
        Scanner intCustomer;
        try {
            // This part loads all book information
            intCustomer = new Scanner(customertxt);
            // This is to increment the discovered client assignment index
            int i = 0;
            // Read lines from the file until no more are left.
            while (intCustomer.hasNext())
            {
                // Read the next line.
                String bEntry = intCustomer.nextLine();
                // Split the line by using the delimiterÂ ":" (semicolon) and store into array.
                matchedID = bEntry.split(":");
//                String temptype = null;
//                if (matchedID[0].contains("STA")) {
//                    temptype = "STA";
//                } else if (matchedID[0].contains("STU")) {
//                    temptype = "STU";
//                }
                // Get the digits out
//                String preOut = matchedID[0].replace(temptype, "");
//                // JOptionPane.showMessageDialog(null, preOut);
//                // Replace the string part with empty digits, leaving only the prefix
//                String numOut = matchedID[0].replace(preOut, "");
                // JOptionPane.showMessageDialog(null, numOut);
                if (i < 200) {
                    if ("true".equals(matchedID[8]) && matchedID[0].contains("CUST")) {
                        matchedID[0] = matchedID[0].replace(CustPrefix, "");
                        CustList.addElement(matchedID[0]);
                        i++;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Maximum client entry limit reached! Stopping at 200th record.", "Client list maxed out!", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
            // OptionPane.showMessageDialog(null, i);
            intCustomer.close();
            // Check if there are no clients at all for each type
            if (CustList.getSize() == 1) {
                CustList.removeAllElements();
                CustList.addElement("No customer(s) available.");
            }
            // Attempt to list all fetched client ID into the list box
            cmbCustID.setModel(CustList);
            // Select index 0 as default
            cmbCustID.setSelectedIndex(0);
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(unnamedBorrowMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     //
     private void custIDIncrementor(){
        // This is to ensure the entire method have access to the matchedID array
        String[] matchedID = null;
        // This flag is to check if the while loop is triggered or not. Triggered while loop indicates presence of records but relevance might not
        boolean hasRecord = false;
        try {
            FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
            // For debugging purpose only
            // JOptionPane.showMessageDialog(null, bID);
            File customertxt = new File(FileDir + "Customer.txt");
            if (!customertxt.exists()) {
                customertxt.createNewFile();
            }
            Scanner inputFile;
            try {
                inputFile = new Scanner(customertxt);
                // Read lines from the file until no more are left.
                while (inputFile.hasNext())
                {
                   // Read the next line.
                   String bEntry = inputFile.nextLine();
                   // Split the line by using the delimiterÂ ":" (semicolon) and store into array.
                   matchedID = bEntry.split(":");
                   String temptype = null;
//                   if (matchedID[0].contains("STA")) {
//                       temptype = "STA";
//                   } else if (matchedID[0].contains("STU")) {
//                       temptype = "STU";
//                   }
                   matchedID[0] = matchedID[0].replace(CustPrefix, "");
                   hasRecord = true;
                }
                inputFile.close();
                if (!hasRecord) {
                    JOptionPane.showMessageDialog(null, "No customer(s) record of any type was found! Restarting database entry.", "Customer database is empty!", JOptionPane.ERROR_MESSAGE);
                    newCustID = 1;
                } else {
                    newCustID = Integer.parseInt(matchedID[0]) + 1;
                }
                // JOptionPane.showMessageDialog(null, newClientID);
            } catch (FileNotFoundException ex) {
                //Logger.getLogger(unnamedBorrowMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "Invalid input! Customer can only consist of numbers", "Invalid input type!", JOptionPane.ERROR_MESSAGE);
        }
    }
     private void loadCustomerInfo(){
        // Assigning the cID to the selected index value
        CustID = (String) cmbCustID.getSelectedItem();
        // This is to ensure the entire method have access to borrow matchedID array
        String[] matchedID = null;
        FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
        // For debugging purpose only
        // JOptionPane.showMessageDialog(null, bID);
        File customertxt = new File(FileDir + "Customer.txt");
        Scanner intCustomer;
        
        try {
            // This part loads all book information
            intCustomer = new Scanner(customertxt);
            // Read lines from the file until no more are left.
            while (intCustomer.hasNext())
            {
                // Read the next line.
                String bEntry = intCustomer.nextLine();
                // Split the line by using the delimiter ":" (semicolon) and store into array.
                matchedID = bEntry.split(":");
                matchedID[0] = matchedID[0].replace(CustPrefix, "");
                
                // JOptionPane.showMessageDialog(null, i);
                if (cmbCustID.getSelectedItem().equals(matchedID[0])) {
                    txtManagerID.setText(matchedID[1]);
                    txtFullName.setText(matchedID[2]);
                    
                    txtPhoneNumber.setText(matchedID[3]);
                    txaHomeAddress.setText(matchedID[4]);
                    switch (matchedID[5]) {
                        case "Male":
                            cmbGender.setSelectedIndex(1);
                            break;
                        case "Female":
                            cmbGender.setSelectedIndex(2);
                            break;
                        default:
                            cmbGender.setSelectedIndex(1);
                    }
                    txtEmail.setText(matchedID[6]);
                    txtDOB.setText(matchedID[7]);
                }
            }
            intCustomer.close();
        } catch (FileNotFoundException ex) {
           // Logger.getLogger(unnamedBorrowMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    private void registerCustomer(){
        // Declaring file extension used
        FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
        // Formatting ID into formal 6-digit mask
        DecimalFormat dc = new DecimalFormat("00000");
        try {
            // Fetching IDs from the textfields
            CustID = dc.format(newCustID);
            // Check if textfields are empty
            emptyFields();
            // Storing Borrowing entries into variables
            // Checking if gender is unselected
            if (cmbGender.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(null, "Gender is unset! Autosetting value to male", "Gender unselected!", JOptionPane.ERROR_MESSAGE);
                cmbGender.setSelectedIndex(1); // Setting the gender to male which is index 1
            }
            String CustFullName = txtFullName.getText();
            String CustPhoneNumber = txtPhoneNumber.getText();
            String CustAddress = txaHomeAddress.getText();
            String CustGender = (String) cmbGender.getSelectedItem();
            String CustEmail = txtDOB.getText();
            String CustDOB = txtDOB.getText();
            // FileWriter and PrintWriter to create and write into book.txt
            try {
                // FileWriter to write into a new file called client.txt
                FileWriter cd = new FileWriter(FileDir + "Customer.txt", true); 
                // PrintWriter to print into client.txt
                PrintWriter cdp = new PrintWriter(cd); 
                // To print the line into Borrowing textfile
                cdp.println(CustPrefix + CustID + ":" +
                            uID + ":" +
                            CustFullName + ":" +
                            CustPhoneNumber + ":" +
                            CustAddress + ":" +
                            CustGender + ":" +
                            CustEmail + ":" + 
                            CustDOB + ":" +
                             "true"); //true boolean indicating the user is exisiting (non-deleted)
                
                cdp.close();
                cd.close();
                // To display completed borrowing process status
                JOptionPane.showMessageDialog(null, "Client is successfully added! Press OK to return to client management form.", "Adding client succeeded!", JOptionPane.INFORMATION_MESSAGE);
                // To refresh new ID 
                custIDIncrementor();
                // JOptionPane.showMessageDialog(null, newClientID);
                // To reload the client information
                // Integrate the reload part with combo box implementation of Client ID
                setCustomerID();
                // Refresh the currently displayed client with the latest ID
                cmbCustID.setSelectedIndex(cmbCustID.getItemCount() - 1);
            } catch (IOException ex) {
                //Logger.getLogger(unnamedBorrowMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch (Exception ex) {
            highlightEmpty();
            JOptionPane.showMessageDialog(null, "Invalid input! Please check your input to proceed.", "Invalid insertion detected!", JOptionPane.ERROR_MESSAGE);
            // Continue with displaying which field was affected. ensure it appears before the mnessagebox
            System.out.println(ex);
        }      
    }
    private void updateCustomerInfo(){
        // TODO add your handling code here:
        try {
            // Check if textfields are empty
            emptyFields();
            // To get directory  
            FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
            // To get the book ID
            CustID = (String) cmbCustID.getSelectedItem();
            // To rename original book.txt to book.bak
            File customerOri = new File(FileDir + "Customer.txt");
            File customerBack = new File(FileDir + "CustomerBack.txt");
            // To check if clientBak.txt is present or not
            if (!customerBack.exists()){
                customerOri.createNewFile();
            }
            // This is for debugging only!
            // JOptionPane.showMessageDialog(null, "renamed");
            // This is to rename the existing book.txt to clientBak.txt
            customerOri.renameTo(customerBack);
            // This is to open, find and replace a specific book record
            // Requires temporary file to store current state
            // FileWriter to write into a new file called book.txt
            FileWriter cd = new FileWriter(FileDir + "Customer.txt"); 
            // PrintWriter to print into book.txt
            PrintWriter cdp = new PrintWriter(cd); 
            // This is to open and read clientBak.txt 
            File customertxt = new File(FileDir + "customerBack.txt");
            // This is to instantiate the file opened earlier
            Scanner inputFile = new Scanner(customertxt);
            // This array is to contain all lines
            String[] matchedID;
            // This is only for debugging!
            // boolean itWorked = false;
            // Read lines from the file until no more are left.
            while (inputFile.hasNext())
            {
                // This is for debugging only!
                // JOptionPane.showMessageDialog(null, "In loop");
                // Read the next line.
                String bEntry = inputFile.nextLine();
                // Split the line by using the delimiter ":" (semicolon) and store into array.
                matchedID = bEntry.split(":");
                // Check if the read line has current book ID
                if (matchedID[0].equals(CustPrefix + CustID)) {
                    // Inserting the new information from the text fields into the book line
                    matchedID[1] = txtManagerID.getText();
                    matchedID[2] = txtFullName.getText();
                    matchedID[3] = txtPhoneNumber.getText();
                    matchedID[4] = txaHomeAddress.getText();
                    matchedID[5] = (String) cmbGender.getSelectedItem();
                    matchedID[6] = txtDOB.getText();
                    matchedID[7] = txtDOB.getText();
                    matchedID[8] = "true";
                    // JOptionPane.showMessageDialog(null, "Yes it worked");
                }
                // Rewrite the new book.txt with values found in clientBak.txt
                cdp.println(matchedID[0] + ":" +
                            matchedID[1] + ":" +
                            matchedID[2] + ":" +
                            matchedID[3] + ":" +
                            matchedID[4] + ":" +
                            matchedID[5] + ":" +
                            matchedID[6] + ":" +
                            matchedID[7] + ":" +
                            matchedID[8]);

            }
            // Close the clientBak.txt reader
            inputFile.close();
            // This deletes clientBak.txt
            customerBack.delete();
            // This closes the book.txt printer 
            cdp.close();
            JOptionPane.showMessageDialog(null, "Client record has been updated!", "Client updated!", JOptionPane.INFORMATION_MESSAGE);
            loadCustomerInfo();
        } catch (Exception ex) {
            highlightEmpty();
            JOptionPane.showMessageDialog(null, "Invalid input! Please check your input to proceed.", "Invalid insertion detected!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void deleteCustomer(){
        // TODO add your handling code here:
        try {
            // To rename original book.txt to book.bak
            File customerOri = new File(FileDir + "Customer.txt");
            File customerBack = new File(FileDir + "CustomerBack.txt");
            // To check if clientBak.txt is present or not
            if (!customerBack.exists()){
                customerOri.createNewFile();
            }
            // This is for debugging only!
            // JOptionPane.showMessageDialog(null, "renamed");
            // This is to rename the existing book.txt to clientBak.txt
            customerOri.renameTo(customerBack);
            // This is to open, find and replace a specific book record
            // Requires temporary file to store current state
            // FileWriter to write into a new file called book.txt
            FileWriter cd = new FileWriter(FileDir + "Customer.txt"); 
            // PrintWriter to print into book.txt
            PrintWriter cdp = new PrintWriter(cd); 
            // This is to open and read clientBak.txt 
            File customertxt = new File(FileDir + "CustomerBack.txt");
            // This is to instantiate the file opened earlier
            Scanner inputFile = new Scanner(customertxt);
            // This array is to contain all lines
            String[] matchedID;
            // This is only for debugging!
            // boolean itWorked = false;
            // Read lines from the file until no more are left.
            while (inputFile.hasNext())
            {
                // This is for debugging only!
                // JOptionPane.showMessageDialog(null, "In loop");
                // Read the next line.
                String cEntry = inputFile.nextLine();
                // Split the line by using the delimiter ":" (semicolon) and store into array.
                matchedID = cEntry.split(":");
                // Check if the read line has current book ID
                if (matchedID[0].equals(CustPrefix + CustID)) {
                    // Setting the deleted flag to false
                    matchedID[8] = "false";
                    // JOptionPane.showMessageDialog(null, "Yes it worked");
                }
                // Rewrite the new book.txt with values found in clientBak.txt
                cdp.println(matchedID[0] + ":" +
                            matchedID[1] + ":" +
                            matchedID[2] + ":" +
                            matchedID[3] + ":" +
                            matchedID[4] + ":" +
                            matchedID[5] + ":" +
                            matchedID[6] + ":" +
                            matchedID[7] + ":" +
                            matchedID[8]);

            }
            // Close the clientBak.txt reader
            inputFile.close();
            // This deletes clientBak.txt
            customerBack.delete();
            // This closes the book.txt printer 
            cdp.close();
            JOptionPane.showMessageDialog(null, "Customer record has been deleted!", "Customer deleted!", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }
     
    //Clear session
    private void clearCache(){
        try {  
            FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
            File cache = new File(FileDir + "UserCache.txt");
            if (cache.exists()) {
                cache.delete();
            }
        } catch (Exception ex) {
            
        }
    }
    
    //form load method during init of the form
     private void initForm(){
        this.setSize(1170,750);
        this.setLocation(600,150);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        
        setCustomerID();
        // Set the initial value for new book
        custIDIncrementor();
        // This anon class handles window closing event
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e){
                int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Closing Window", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (selection == JOptionPane.YES_OPTION) {
                    clearCache();
                    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } else {
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }
        });
        txaHomeAddress.getDocument().putProperty("filterNewlines", Boolean.TRUE);
        inputCharacterValidation();
     }
     
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Validation Methods">
     private void emptyFields() throws Exception {
        APUEmailValidation vd = new APUEmailValidation();
        
        if ("".equals(txtFullName.getText())) {
            throw new Exception("Empty customer name");
        }
        if ("".equals(txaHomeAddress.getText())) {
            throw new Exception("Empty customer home address");
        }
        if ("          ".equals(txtPhoneNumber.getText())) {
            throw new Exception("Empty phone number");
        }
        if("".equals(txtEmail.getText())){
            throw new Exception("Empty email");
        }
        if ("".equals(txtDOB.getText())) {
            throw new Exception("Empty customer date of birth");
        }
        if("".equals(txtManagerID.getText())){
            throw new Exception("Empty Manager ID");
        }
        if (vd.runValidate(txtDOB, false)) {
            throw new Exception("Invalid DOB format");
        }
         if (vd.runValidate(txtEmail, false)) {
            throw new Exception("Invalid email format");
        }
    }
     
     private void clearUser(){
        txtFullName.setText("");
        txtPhoneNumber.setText("");
        txaHomeAddress.setText("");
        txtDOB.setText("");
        txtDOB.setText("");
        txtManagerID.setText("");
        cmbGender.setSelectedIndex(0);
        CustID = "";
    }
     private void highlightEmpty() {
        if("".equals(txtFullName.getText())) {
            lblFullName.setForeground(Color.RED);
        }
        if("          ".equals(txtPhoneNumber.getText())) {
            lblPhoneNumber.setForeground(Color.RED);
        }
        if("".equals(txaHomeAddress.getText())) {
            lblHomeAddress.setForeground(Color.RED);
        }
        if("".equals(txtDOB.getText())){
            lblEmail.setForeground(Color.RED);
        }
        if("".equals(txtDOB.getText())){
            lblDOB.setForeground(Color.RED);
        }
        if("".equals(txtManagerID.getText())) {
            lblManagerID.setForeground(Color.RED);
        }
    }
      private void deHighlightEmpty(){
        lblHomeAddress.setForeground(ogtxt);
        lblDOB.setForeground(ogtxt);
        lblPhoneNumber.setForeground(ogtxt);
        lblEmail.setForeground(ogtxt);
        lblFullName.setForeground(ogtxt);
       // lblClientHomeAddress.setForeground(ogtxt);
    }
    private void inputCharacterValidation(){
        txtFullName.getDocument().addDocumentListener(new APUDocumentListener() {
            APUFullNameValidation vd = new APUFullNameValidation();
            @Override
            public void changedUpdate(DocumentEvent e){
                vd.runValidate(txtFullName);
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                vd.runValidate(txtFullName);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                vd.runValidate(txtFullName);
            }
            
        });
        txaHomeAddress.getDocument().addDocumentListener(new APUDocumentListener() {
            APUAddressValidation vd = new APUAddressValidation();
            @Override
            public void changedUpdate(DocumentEvent e){
                vd.runValidate(txaHomeAddress);
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                vd.runValidate(txaHomeAddress);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                vd.runValidate(txaHomeAddress);
            }
        });
    }
    // </editor-fold>  
    
    // <editor-fold defaultstate="collapsed" desc="Button Events">
    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        deHighlightEmpty();
        registerCustomer();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cmbCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustIDActionPerformed
        // TODO add your handling code here:
        clearUser();
        if (cmbCustID.getSelectedIndex() > 0) {
            loadCustomerInfo();
            btnRegister.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            
        } else {
            // Disabling action buttons when no book is loaded. Add button is still available to accept new book
            btnRegister.setEnabled(true);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            //txtManagerID.setVisible(false);
        }
    }//GEN-LAST:event_cmbCustIDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateCustomerInfo();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete customer record?", "Deleting customer", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (selection == JOptionPane.YES_OPTION) {
                deleteCustomer();
                loadCustomerInfo();
                } else {
                    JOptionPane.showMessageDialog(null, "Customer record has not been deleted!", "Customer deletion", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtDOBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBFocusLost
       DOBValidation vd = new DOBValidation();
       vd.runValidate(txtDOB, true);
    }//GEN-LAST:event_txtDOBFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        APUEmailValidation vd = new APUEmailValidation();     
        vd.runValidate(txtEmail, true);
    }//GEN-LAST:event_txtEmailFocusLost
    //</editor-fold>
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APUManageCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCustID;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblManagerID;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txaHomeAddress;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtManagerID;
    private javax.swing.JFormattedTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
