/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kxbjava;

import com.formdev.flatlaf.FlatDarkLaf;
import com.itextpdf.io.exceptions.IOException;
import static com.itextpdf.kernel.colors.ColorConstants.BLACK;
import static com.itextpdf.kernel.colors.ColorConstants.BLUE;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.Style;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageFeedback extends javax.swing.JFrame {

    private String FileDir, feedID, apptid, techid, status, feedback;
    private boolean filter = false;
    /**
     * Creates new form ViewFeedback
     */
    public ManageFeedback() throws java.io.IOException {
        initComponents();
        initForm();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeedback = new javax.swing.JTable();
        txtFeedback = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtFilter = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(68, 68, 68));

        lblTitle.setBackground(new java.awt.Color(68, 68, 68));
        lblTitle.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(218, 0, 55));
        lblTitle.setText("Manage Feedback");

        tblFeedback.setBackground(new java.awt.Color(68, 68, 68));
        tblFeedback.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblFeedback.setForeground(new java.awt.Color(237, 237, 237));
        tblFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Feedback ID", "Appointment ID", "Technician ID", "Payment Status", "Feedback"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFeedbackMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFeedback);

        txtFeedback.setBackground(new java.awt.Color(68, 68, 68));
        txtFeedback.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtFeedback.setForeground(new java.awt.Color(237, 237, 237));
        txtFeedback.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(237, 237, 237)));
        txtFeedback.setCaretColor(new java.awt.Color(237, 237, 237));

        btnFilter.setBackground(new java.awt.Color(23, 23, 23));
        btnFilter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnFilter.setForeground(new java.awt.Color(237, 237, 237));
        btnFilter.setText("Filter Records");
        btnFilter.setBorder(null);
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(23, 23, 23));
        btnUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(237, 237, 237));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtFilter.setBackground(new java.awt.Color(68, 68, 68));
        txtFilter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtFilter.setForeground(new java.awt.Color(237, 237, 237));
        txtFilter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(237, 237, 237)));
        txtFilter.setCaretColor(new java.awt.Color(237, 237, 237));
        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Button Events">   
    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed

        clearTable();
        try {
            if(filterFeedback()){
                JOptionPane.showMessageDialog(null, "Record(s) filtered accordingly", "Records Filtered!", JOptionPane.INFORMATION_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(null, "No record(s) found according to the filter", "No Record(s)", JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.io.IOException ex) {
            Logger.getLogger(ManageFeedback.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     // TODO add your handling code here:
     updateUserInfo();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterActionPerformed

    private void tblFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFeedbackMouseClicked
        // TODO add your handling code here:
        selectRow();
    }//GEN-LAST:event_tblFeedbackMouseClicked

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Methods">   
    
    
    private void selectRow(){
        int i = tblFeedback.getSelectedRow();
        
        feedID = tblFeedback.getValueAt(i, 0).toString();
        apptid = tblFeedback.getValueAt(i, 1).toString();
        techid = tblFeedback.getValueAt(i, 2).toString();
        status = tblFeedback.getValueAt(i, 3).toString();
        feedback = tblFeedback.getValueAt(i, 4).toString();
        
        
        txtFeedback.setText(feedback);
        
    }
    
//    private void printRecords() throws FileNotFoundException{
//        
//           
//            PdfWriter writer = new PdfWriter(pdfsource);
//            PdfDocument pdfdoc = new PdfDocument(writer);
//            Document document = new Document(pdfdoc);
//            
//            Style titlestyle = new Style();
//            titlestyle.setBold()
//                      .setFontSize(18f)
//                      .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER);
//            
//            String title = "Feedback Records of the Customers";
//            Paragraph doctitle = new Paragraph(title).addStyle(titlestyle);
//            
//            float columnWidth[] = {150f,150f,150f,150f,150f};
//            Table tbl = new Table(columnWidth);
//           // doc.addTitle("AHHASC");
//            document.add(doctitle);
//            tbl.addCell("Feedback ID").setFontColor(new DeviceRgb(23, 23, 23));
//            tbl.addCell("Appointment ID").setFontColor(new DeviceRgb(23, 23, 23));
//            tbl.addCell("Technician ID").setFontColor(new DeviceRgb(23, 23, 23));
//            tbl.addCell("Payment Status").setFontColor(new DeviceRgb(23, 23, 23));
//            tbl.addCell("Feedback").setFontColor(new DeviceRgb(23, 23, 23));
//            
//            
//            for(int i = 0; i < tblFeedback.getRowCount(); i++){
//                String feedID = tblFeedback.getValueAt(i, 0).toString();
//                String apptID = tblFeedback.getValueAt(i, 1).toString();
//                String techID = tblFeedback.getValueAt(i, 2).toString();
//                String Status = tblFeedback.getValueAt(i, 3).toString();
//                String feedback = tblFeedback.getValueAt(i, 4).toString();
//                
//                tbl.addCell(feedID);
//                tbl.addCell(apptID);
//                tbl.addCell(techID);
//                tbl.addCell(Status);
//                tbl.addCell(feedback);
//                
//            }
//            
//           //write into the pdf
//           document.add(tbl);
//           document.close();
//        
//       JOptionPane.showMessageDialog(null, "Printed to PDF Successfully!", "Records Printed!", JOptionPane.INFORMATION_MESSAGE);
//    
//    }
     private void updateUserInfo() {
        // TODO add your handling code here:
        try {
            // Check if textfields are empty
           // emptyFields();
           // if (emailChecker()) {
           ///     throw new Exception("There is account with this email. Email cannot be used");
           //}
           // if (usernameChecker()) {
           //     throw new Exception("Username is taken. Username Duplicated!");
           // }
            // To get directory  
            
            
            FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
            // To get the book ID
            //uID = (String) cmbUserID.getSelectedItem();
            // To rename original book.txt to book.bak
            File feedori = new File(FileDir + "Feedback.txt");
            File feedbak = new File(FileDir + "FeedbackBack.txt");
            // To check if clientBak.txt is present or not
            if (!feedbak.exists()) {
                feedori.createNewFile();
            }
            // This is for debugging only!
            // JOptionPane.showMessageDialog(null, "renamed");
            // This is to rename the existing book.txt to clientBak.txt
            feedori.renameTo(feedbak);
            // This is to open, find and replace a specific book record
            // Requires temporary file to store current state
            // FileWriter to write into a new file called book.txt
            FileWriter cd = new FileWriter(FileDir + "Feedback.txt");
            // PrintWriter to print into book.txt
            PrintWriter cdp = new PrintWriter(cd);
            // This is to open and read clientBak.txt 
            File usertxt = new File(FileDir + "FeedbackBack.txt");
            // This is to instantiate the file opened earlier
            Scanner inputFile = new Scanner(usertxt);
            // This array is to contain all lines
            String[] matchedID;
            // This is only for debugging!
            // boolean itWorked = false;
            // Read lines from the file until no more are left.
            while (inputFile.hasNext()) {
                // This is for debugging only!
                // JOptionPane.showMessageDialog(null, "In loop");
                // Read the next line.
                String bEntry = inputFile.nextLine();
                // Split the line by using the delimiter ":" (semicolon) and store into array.
                matchedID = bEntry.split(":");
                // Check if the read line has current book ID
                if (matchedID[0].equals(feedID)) {
                    // Inserting the new information from the text fields into the book line
                    matchedID[1] = apptid;
                    matchedID[2] = techid;
                    matchedID[3] = status;
                    matchedID[4] = txtFeedback.getText();
                    matchedID[5] = "true";
                   // matchedID[5] = "true";
                   
                    
                    // JOptionPane.showMessageDialog(null, "Yes it worked");
                }
                // Rewrite the new book.txt with values found in clientBak.txt
                cdp.println(matchedID[0] + ":"
                        + matchedID[1] + ":"
                        + matchedID[2] + ":"
                        + matchedID[3] + ":"
                        + matchedID[4] + ":" 
                        + matchedID[5]);

            }
            // Close the clientBak.txt reader
            inputFile.close();
            // This deletes clientBak.txt
            feedbak.delete();
            // This closes the book.txt printer 
            cdp.close();
            JOptionPane.showMessageDialog(null, "Client record has been updated!", "Client updated!", JOptionPane.INFORMATION_MESSAGE);
           // loadUserInfo();
        } catch (Exception ex) {
            System.out.println(ex);
            //highlightEmpty();
            // if (emailChecker()) {
            //    JOptionPane.showMessageDialog(null, "There is account with this email. Email cannot be used", "Duplicated Email", JOptionPane.WARNING_MESSAGE);
           // }
            //if (usernameChecker()) {
           //   JOptionPane.showMessageDialog(null, "Username is taken! Use a different username to proceed.", "Username is in use!", JOptionPane.WARNING_MESSAGE);  
           // }
            JOptionPane.showMessageDialog(null, "Invalid input! Please check your input to proceed.", "Invalid insertion detected!", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void insertFeedbackRecords() throws java.io.IOException{
        try {
             FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
             File feedtxt = new File(FileDir + "Feedback.txt");
             BufferedReader br = new BufferedReader(new FileReader(feedtxt));
            Object[] tableLines = br.lines().toArray();
            DefaultTableModel model = (DefaultTableModel)tblFeedback.getModel();
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(":");
                //if(txticpass.getText().equals(dataRow[1])){
                     model.addRow(dataRow);
              //  }
             
        }
            br.close();
        }
        catch (FileNotFoundException ex){
            Logger.getLogger(LoginRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private boolean filterFeedback() throws java.io.IOException{
        boolean Records = false;
        try {
             
             FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
             File feedtxt = new File(FileDir + "Feedback.txt");
             BufferedReader br = new BufferedReader(new FileReader(feedtxt));
            Object[] tableLines = br.lines().toArray();
            DefaultTableModel model = (DefaultTableModel)tblFeedback.getModel();
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(":");
                if(dataRow[0].contains(txtFeedback.getText()) || dataRow[1].contains(txtFeedback.getText()) || dataRow[2].contains(txtFeedback.getText()) || dataRow[3].contains(txtFeedback.getText()) || dataRow[4].contains(txtFeedback.getText())){
                     model.addRow(dataRow);
                     Records = true;
                     
               }
            }
             br.close();
        }
        catch (FileNotFoundException ex){
           Logger.getLogger(ManageFeedback.class.getName()).log(Level.SEVERE, null, ex);
       }
         return Records;
    }
//    private void updateFeedback(){
//        try {
//            // Check if textfields are empty
//            emptyFields();
//            // To get directory  
//            FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
//            // To get the book ID
//            CustID = (String) cmbCustID.getSelectedItem();
//            // To rename original book.txt to book.bak
//            File customerOri = new File(FileDir + "Customer.txt");
//            File customerBack = new File(FileDir + "CustomerBack.txt");
//            // To check if clientBak.txt is present or not
//            if (!customerBack.exists()){
//                customerOri.createNewFile();
//            }
//            // This is for debugging only!
//            // JOptionPane.showMessageDialog(null, "renamed");
//            // This is to rename the existing book.txt to clientBak.txt
//            customerOri.renameTo(customerBack);
//            // This is to open, find and replace a specific book record
//            // Requires temporary file to store current state
//            // FileWriter to write into a new file called book.txt
//            FileWriter cd = new FileWriter(FileDir + "Customer.txt"); 
//            // PrintWriter to print into book.txt
//            PrintWriter cdp = new PrintWriter(cd); 
//            // This is to open and read clientBak.txt 
//            File customertxt = new File(FileDir + "customerBack.txt");
//            // This is to instantiate the file opened earlier
//            Scanner inputFile = new Scanner(customertxt);
//            // This array is to contain all lines
//            String[] matchedID;
//            // This is only for debugging!
//            // boolean itWorked = false;
//            // Read lines from the file until no more are left.
//            while (inputFile.hasNext())
//            {
//                // This is for debugging only!
//                // JOptionPane.showMessageDialog(null, "In loop");
//                // Read the next line.
//                String bEntry = inputFile.nextLine();
//                // Split the line by using the delimiter ":" (semicolon) and store into array.
//                matchedID = bEntry.split(":");
//                // Check if the read line has current book ID
//                if (matchedID[0].equals(CustPrefix + CustID)) {
//                    // Inserting the new information from the text fields into the book line
//                    matchedID[1] = txtManagerID.getText();
//                    matchedID[2] = txtFullName.getText();
//                    matchedID[3] = txtPhoneNumber.getText();
//                    matchedID[4] = txaHomeAddress.getText();
//                    matchedID[5] = (String) cmbGender.getSelectedItem();
//                    matchedID[6] = txtDOB.getText();
//                    matchedID[7] = txtDOB.getText();
//                    matchedID[8] = "true";
//                    // JOptionPane.showMessageDialog(null, "Yes it worked");
//                }
//                // Rewrite the new book.txt with values found in clientBak.txt
//                cdp.println(matchedID[0] + ":" +
//                            matchedID[1] + ":" +
//                            matchedID[2] + ":" +
//                            matchedID[3] + ":" +
//                            matchedID[4] + ":" +
//                            matchedID[5] + ":" +
//                            matchedID[6] + ":" +
//                            matchedID[7] + ":" +
//                            matchedID[8]);
//
//            }
//            // Close the clientBak.txt reader
//            inputFile.close();
//            // This deletes clientBak.txt
//            customerBack.delete();
//            // This closes the book.txt printer 
//            cdp.close();
//            JOptionPane.showMessageDialog(null, "Client record has been updated!", "Client updated!", JOptionPane.INFORMATION_MESSAGE);
//            loadCustomerInfo();
//        } catch (Exception ex) {
//            highlightEmpty();
//            JOptionPane.showMessageDialog(null, "Invalid input! Please check your input to proceed.", "Invalid insertion detected!", JOptionPane.ERROR_MESSAGE);
//        }
//    }
//    
    private void clearTable(){
        DefaultTableModel model = (DefaultTableModel)tblFeedback.getModel();
        while(model.getRowCount()>0){
            model.removeRow(0);
        }
    }
     //<editor-fold defaultstate="collapsed" desc="Validation Methods">
         private void inputCharacterValidation(){
        txtFeedback.getDocument().addDocumentListener(new APUDocumentListener() {
            filterValidation vd = new filterValidation();
            @Override
            public void changedUpdate(DocumentEvent e){
                vd.runValidate(txtFeedback);
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                vd.runValidate(txtFeedback);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                vd.runValidate(txtFeedback);
            }
            
        });
    }
    private void showLoginButton(){
        if (filter){
            btnFilter.setVisible(true);
        }
        else
        {
            btnFilter.setVisible(false);
        }
     } 
    private void showLoginButton(JTextField txt){
        if ("".equals(txt.getText())){
            filter = false;
        } 
        else {
            filter = true;
        }
        showLoginButton();
     }
    
    // </editor-fold>
    
    
    private void clearCache(){
        try {  
            FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
            File cache = new File(FileDir + "UserCache.txt");
            if (cache.exists()) {
                cache.delete();
            }
        } catch (Exception ex) {
            
        }
    }     
     private void initForm() throws java.io.IOException{
        //this.setSize(1170,750);
        //this.setLocation(600,150);
        //btnUpdate.setEnabled(false);
       // btnDelete.setEnabled(false);
        insertFeedbackRecords();
        btnFilter.setVisible(false);
        // Set the initial value for new book
        // This anon class handles window closing event
         txtFeedback.getDocument().addDocumentListener(new APUDocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                showLoginButton(txtFeedback);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                showLoginButton(txtFeedback);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                showLoginButton(txtFeedback);

            }
        });
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e){
                int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Closing Window", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (selection == JOptionPane.YES_OPTION) {
                    clearCache();
                    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } else {
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }
        });
        inputCharacterValidation();
     }
    
     // </editor-fold>
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code">
         try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Fail Look and Feel");
        }
       // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageFeedback().setVisible(true);
                } catch (java.io.IOException ex) {
                    Logger.getLogger(ManageFeedback.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblFeedback;
    private javax.swing.JTextField txtFeedback;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
