/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kxbjava;

import com.formdev.flatlaf.FlatDarkLaf;
import com.itextpdf.io.exceptions.IOException;
import static com.itextpdf.kernel.colors.ColorConstants.BLACK;
import static com.itextpdf.kernel.colors.ColorConstants.BLUE;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.Style;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ViewPayment extends javax.swing.JFrame {

    private String FileDir;
    private boolean filter = false;
    private final String pdfsource = System.getProperty("user.dir") + "\\src\\PDF\\Payment.pdf";
    /**
     * Creates new form ViewFeedback
     */
    public ViewPayment() {
        initComponents();
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeedback = new javax.swing.JTable();
        txtFilter = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(68, 68, 68));

        lblTitle.setBackground(new java.awt.Color(68, 68, 68));
        lblTitle.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(218, 0, 55));
        lblTitle.setText("View Payment");

        tblFeedback.setBackground(new java.awt.Color(68, 68, 68));
        tblFeedback.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblFeedback.setForeground(new java.awt.Color(237, 237, 237));
        tblFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Appointment ID", "Technician ID", "Customer Name", "Appointment Date", "Appointment Time", "Appliance", "Payment Status", "Payment Date", "Total Amount", "Payment Amount", "Balance Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFeedback);

        txtFilter.setBackground(new java.awt.Color(68, 68, 68));
        txtFilter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtFilter.setForeground(new java.awt.Color(237, 237, 237));
        txtFilter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(237, 237, 237)));
        txtFilter.setCaretColor(new java.awt.Color(237, 237, 237));

        btnFilter.setBackground(new java.awt.Color(23, 23, 23));
        btnFilter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnFilter.setForeground(new java.awt.Color(237, 237, 237));
        btnFilter.setText("Filter Records");
        btnFilter.setBorder(null);
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(23, 23, 23));
        btnPrint.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(237, 237, 237));
        btnPrint.setText("Print Login Records");
        btnPrint.setBorder(null);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(lblTitle)))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Button Events">   
    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed

        clearTable();
        if(filterPayment()){
            JOptionPane.showMessageDialog(null, "Record(s) filtered accordingly", "Records Filtered!", JOptionPane.INFORMATION_MESSAGE);
        } else{
            JOptionPane.showMessageDialog(null, "No record(s) found according to the filter", "No Record(s)", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            printRecords();
        } catch (IOException | FileNotFoundException ex) {
            Logger.getLogger(LoginRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Methods">   
    private void printRecords() throws IOException, FileNotFoundException{
        
           
            PdfWriter writer = new PdfWriter(pdfsource);
            PdfDocument pdfdoc = new PdfDocument(writer);
            pdfdoc.setDefaultPageSize(PageSize.A4.rotate());
            Document document = new Document(pdfdoc);
            
            Style titlestyle = new Style();
            titlestyle.setBold()
                      .setFontSize(18f)
                      .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER);
            
            String title = "Payment Records of the Customers";
            Paragraph doctitle = new Paragraph(title).addStyle(titlestyle);
            
            float columnWidth[] = {30f,30f,30f,30f,30f,30f,30f,30f,30f,30f,30f,30f};
            Table tbl = new Table(columnWidth);
           // doc.addTitle("AHHASC");
            document.add(doctitle);
            tbl.addCell("Payment ID").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Appointment ID").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Technician ID").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Customer Name").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Appointment Date").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Appointment Time").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Appliance").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Payment Status").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Payment Date").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Total Amount").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Payment Amount").setFontColor(new DeviceRgb(23, 23, 23));
            tbl.addCell("Balance Amount").setFontColor(new DeviceRgb(23, 23, 23));
                    
            
            
            for(int i = 0; i < tblFeedback.getRowCount(); i++){
                String paymentID = tblFeedback.getValueAt(i, 0).toString();
                String apptID = tblFeedback.getValueAt(i, 1).toString();
                String techID = tblFeedback.getValueAt(i, 2).toString();
                String custName = tblFeedback.getValueAt(i, 3).toString();
                String apptDate = tblFeedback.getValueAt(i, 4).toString();
                String apptTime = tblFeedback.getValueAt(i, 5).toString();
                String appliance = tblFeedback.getValueAt(i, 6).toString();
                String paymentStatus = tblFeedback.getValueAt(i, 7).toString();
                String paymentDate = tblFeedback.getValueAt(i, 8).toString();
                String totalAmount = tblFeedback.getValueAt(i, 9).toString();
                String paymentAmount = tblFeedback.getValueAt(i, 10).toString();
                String balanceAmount = tblFeedback.getValueAt(i, 11).toString();
                
                tbl.addCell(paymentID);
                tbl.addCell(apptID);
                tbl.addCell(techID);
                tbl.addCell(custName);
                tbl.addCell(apptDate);
                tbl.addCell(apptTime);
                tbl.addCell(appliance);
                tbl.addCell(paymentStatus);
                tbl.addCell(paymentDate);
                tbl.addCell(totalAmount);
                tbl.addCell(paymentAmount);
                tbl.addCell(balanceAmount);
                
            }
            
           //write into the pdf
           document.add(tbl);
           document.close();
        
       JOptionPane.showMessageDialog(null, "Printed to PDF Successfully!", "Records Printed!", JOptionPane.INFORMATION_MESSAGE);
    
    }
    private void insertPaymentRecords(){
        try {
             FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
             File paymenttxt = new File(FileDir + "Payment.txt");
             BufferedReader br = new BufferedReader(new FileReader(paymenttxt));
            Object[] tableLines = br.lines().toArray();
            DefaultTableModel model = (DefaultTableModel)tblFeedback.getModel();
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(":");
                //if(txticpass.getText().equals(dataRow[1])){
                     model.addRow(dataRow);
              //  }
             
        }
        }
        catch (FileNotFoundException ex){
            Logger.getLogger(LoginRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private boolean filterPayment(){
        boolean Records = false;
        try {
             
             FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
             File paymenttxt = new File(FileDir + "Payment.txt");
             BufferedReader br = new BufferedReader(new FileReader(paymenttxt));
            Object[] tableLines = br.lines().toArray();
            DefaultTableModel model = (DefaultTableModel)tblFeedback.getModel();
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(":");
               if(dataRow[0].contains(txtFilter.getText()) || dataRow[1].contains(txtFilter.getText()) || dataRow[2].contains(txtFilter.getText()) || dataRow[3].contains(txtFilter.getText()) || dataRow[4].contains(txtFilter.getText())
                    || dataRow[5].contains(txtFilter.getText()) || dataRow[6].contains(txtFilter.getText()) || dataRow[7].contains(txtFilter.getText()) || dataRow[8].contains(txtFilter.getText()) || dataRow[9].contains(txtFilter.getText())
                       || dataRow[10].contains(txtFilter.getText()) || dataRow[11].contains(txtFilter.getText())){
                     model.addRow(dataRow);
                     Records = true;
                     
               }
            }
             
        }
        catch (FileNotFoundException ex){
           Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
       }
         return Records;
    }
    
    
    private void clearTable(){
        DefaultTableModel model = (DefaultTableModel)tblFeedback.getModel();
        while(model.getRowCount()>0){
            model.removeRow(0);
        }
    }
    
     //<editor-fold defaultstate="collapsed" desc="Validation Methods">
         private void inputCharacterValidation(){
        txtFilter.getDocument().addDocumentListener(new APUDocumentListener() {
            filterValidation vd = new filterValidation();
            @Override
            public void changedUpdate(DocumentEvent e){
                vd.runValidate(txtFilter);
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                vd.runValidate(txtFilter);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                vd.runValidate(txtFilter);
            }
            
        });
    }
    private void showLoginButton(){
        if (filter){
            btnFilter.setVisible(true);
        }
        else
        {
            btnFilter.setVisible(false);
        }
     } 
    private void showLoginButton(JTextField txt){
        if ("".equals(txt.getText())){
            filter = false;
        } 
        else {
            filter = true;
        }
        showLoginButton();
     }
    
    // </editor-fold>
    
    
    private void clearCache(){
        try {  
            FileDir = System.getProperty("user.dir") + "\\src\\TextFiles\\";
            File cache = new File(FileDir + "UserCache.txt");
            if (cache.exists()) {
                cache.delete();
            }
        } catch (Exception ex) {
            
        }
    }     
     private void initForm(){
        //this.setSize(1170,750);
        //this.setLocation(600,150);
        //btnUpdate.setEnabled(false);
       // btnDelete.setEnabled(false);
        insertPaymentRecords();
        btnFilter.setVisible(false);
        // Set the initial value for new book
        // This anon class handles window closing event
         txtFilter.getDocument().addDocumentListener(new APUDocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                showLoginButton(txtFilter);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                showLoginButton(txtFilter);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                showLoginButton(txtFilter);

            }
        });
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e){
                int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Closing Window", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (selection == JOptionPane.YES_OPTION) {
                    clearCache();
                    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } else {
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }
        });
        inputCharacterValidation();
     }
    
     // </editor-fold>
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code">
         try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Fail Look and Feel");
        }
       // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnPrint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblFeedback;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
